In [14]:

import numpy as np
import pandas as pd

In [15]:
dat = pd.read_csv("Customer_dim.csv")

In [16]:
dat

,Timestamp,Participant_ID,Gender,Nationality,Age,Food,Juice,Dessert
0,2019/05/07 2:59:13 PM GMT+8,FPS001,Male,Indian,24,Traditional food,Fresh Juice,Maybe
1,2019/05/07 2:59:45 PM GMT+8,FPS002,Female,Indian,22,Western Food,Carbonated drinks,Yes
2,2019/05/07 3:00:05 PM GMT+8,FPS003,Male,Indian,31,Western Food,Fresh Juice,Maybe
3,2019/05/07 3:00:11 PM GMT+8,FPS004,Female,Indian,25,Traditional food,Fresh Juice,Maybe
4,2019/05/07 3:02:50 PM GMT+8,FPS005,Male,Indian,27,Traditional food,Fresh Juice,Maybe
...,...,...,...,...,...,...,...,...
283,2019/05/10 9:24:00 AM GMT+8,FPS284,Male,Indian,27,Western Food,Fresh Juice,Yes
284,2019/05/10 9:32:54 AM GMT+8,FPS285,Male,Indian,24,Traditional food,Fresh Juice,Yes
285,2019/05/10 12:09:17 PM GMT+8,FPS286,Male,Indian,25,Traditional food,Fresh Juice,Yes
286,2019/05/10 12:52:17 PM GMT+8,FPS287,Male,Indian,27,Traditional food,Fresh Juice,Yes
287,2019/05/10 12:55:42 PM GMT+8,FPS288,Male,Indian,27,Traditional food,Fresh Juice,No

In [17]:
#df = pd.DataFrame(data)
 
# Define new data for additional columns
#age = [22, 25, 23, 24]
#state = ['NCT', 'Karnataka', 'Tamil Nadu', 'Bihar']
 
# Add multiple columns using dictionary assignment
#new_data = {'Age': age, 'State': state }
#df = df.assign(**new_data)
 
#NAprint(df)

In [18]:
Nombres = pd.read_excel("/Users/victormorenorequena/Desktop/My_Projects/trueque nombres.xlsx")

In [19]:
Nombres["Names"]

0      José Luis Palomino
1          Nicolás Freire
2           Miguel Torrén
3          Matías Caruzzo
4              Juan Sabia
              ...
283          Agustín Aleo
284           Enzo Ybáñez
285            Román Vega
286         Luciano Gómez
287     Jonathan Sandoval
Name: Names, Length: 288, dtype: object

In [20]:
combined = pd.merge(dat, Nombres, how="inner", on="Participant_ID")
combined

,Timestamp,Participant_ID,Gender,Nationality,Age,Food,Juice,Dessert,Names
0,2019/05/07 2:59:13 PM GMT+8,FPS001,Male,Indian,24,Traditional food,Fresh Juice,Maybe,José Luis Palomino
1,2019/05/07 2:59:45 PM GMT+8,FPS002,Female,Indian,22,Western Food,Carbonated drinks,Yes,Nicolás Freire
2,2019/05/07 3:00:05 PM GMT+8,FPS003,Male,Indian,31,Western Food,Fresh Juice,Maybe,Miguel Torrén
3,2019/05/07 3:00:11 PM GMT+8,FPS004,Female,Indian,25,Traditional food,Fresh Juice,Maybe,Matías Caruzzo
4,2019/05/07 3:02:50 PM GMT+8,FPS005,Male,Indian,27,Traditional food,Fresh Juice,Maybe,Juan Sabia
...,...,...,...,...,...,...,...,...,...
283,2019/05/10 9:24:00 AM GMT+8,FPS284,Male,Indian,27,Western Food,Fresh Juice,Yes,Agustín Aleo
284,2019/05/10 9:32:54 AM GMT+8,FPS285,Male,Indian,24,Traditional food,Fresh Juice,Yes,Enzo Ybáñez
285,2019/05/10 12:09:17 PM GMT+8,FPS286,Male,Indian,25,Traditional food,Fresh Juice,Yes,Román Vega
286,2019/05/10 12:52:17 PM GMT+8,FPS287,Male,Indian,27,Traditional food,Fresh Juice,Yes,Luciano Gómez
287,2019/05/10 12:55:42 PM GMT+8,FPS288,Male,Indian,27,Traditional food,Fresh Juice,No,Jonathan Sandoval

In [22]:
combined.to_csv('Customer_ID_FINAL.csv', index=False)